name: Release SDK Packages

on:
  push:
    tags:
      - '@qriptoagentiq/core-client@*'
      - '@qriptoagentiq/kn0w1-client@*'
      - '@qriptoagentiq/a2a-client@*'
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies (workspace-safe)
        run: npm install --workspaces --include-workspace-root --no-audit --no-fund

      - name: Configure npm auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          npm whoami || true

      - name: Diagnostics (npm access)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Listing packages for current user (may be limited):"
          npm access ls-packages 2>/dev/null || true
          echo "npm config list:"
          npm config list -l | sed -n '1,120p'

      - name: Test SDK workspaces
        run: npm run test

      - name: Build SDK workspaces
        run: npm run build:sdk

      - name: Publish changed (scaffold)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node ./scripts/publish.js
